import {
  Atom,
  Binary,
  Book,
  BookOpen,
  Books,
  Brain,
  BracketsCurly,
  Bug,
  Calculator,
  Certificate,
  ChalkboardTeacher,
  ChartBar,
  ChartLineUp,
  ChartPie,
  Circuitry,
  Cloud,
  Code,
  Compass,
  Cpu,
  Cube,
  CurrencyDollar,
  Database,
  Desktop,
  DeviceMobile,
  Equals,
  FileCode,
  Flask,
  Function as FunctionIcon,
  Gear,
  GitBranch,
  Globe,
  Graph,
  HardDrive,
  Infinity as InfinityIcon,
  Eye,
  Laptop,
  Lightbulb,
  MathOperations,
  Network,
  PaintBrush,
  Palette,
  PuzzlePiece,
  Robot,
  Rocket,
  Ruler,
  Scan,
  ShieldCheck,
  Sigma,
  Sparkle,
  Stack,
  Student,
  Target,
  Terminal,
  TerminalWindow,
  TreeStructure,
  Vault,
  Waveform,
  WifiHigh,
  Wrench,
} from '@phosphor-icons/react'

export const ADMIN_ICON_OPTIONS = [
  { name: 'Atom', label: 'Atom', Icon: Atom },
  { name: 'Binary', label: 'Binary', Icon: Binary },
  { name: 'Book', label: 'Book', Icon: Book },
  { name: 'BookOpen', label: 'Open Book', Icon: BookOpen },
  { name: 'Books', label: 'Books', Icon: Books },
  { name: 'Brain', label: 'Brain', Icon: Brain },
  { name: 'BracketsCurly', label: 'Code Brackets', Icon: BracketsCurly },
  { name: 'Bug', label: 'Debugging', Icon: Bug },
  { name: 'Calculator', label: 'Calculator', Icon: Calculator },
  { name: 'Certificate', label: 'Certificate', Icon: Certificate },
  { name: 'ChalkboardTeacher', label: 'Teaching', Icon: ChalkboardTeacher },
  { name: 'ChartBar', label: 'Bar Chart', Icon: ChartBar },
  { name: 'ChartLineUp', label: 'Chart', Icon: ChartLineUp },
  { name: 'ChartPie', label: 'Pie Chart', Icon: ChartPie },
  { name: 'Circuitry', label: 'Circuitry', Icon: Circuitry },
  { name: 'Cloud', label: 'Cloud', Icon: Cloud },
  { name: 'Code', label: 'Code', Icon: Code },
  { name: 'Compass', label: 'Compass', Icon: Compass },
  { name: 'Cube', label: 'Cube', Icon: Cube },
  { name: 'CurrencyDollar', label: 'Finance', Icon: CurrencyDollar },
  { name: 'Database', label: 'Database', Icon: Database },
  { name: 'Desktop', label: 'Desktop', Icon: Desktop },
  { name: 'DeviceMobile', label: 'Mobile', Icon: DeviceMobile },
  { name: 'Equals', label: 'Equals', Icon: Equals },
  { name: 'FileCode', label: 'File Code', Icon: FileCode },
  { name: 'Flask', label: 'Lab', Icon: Flask },
  { name: 'FunctionIcon', label: 'Function', Icon: FunctionIcon },
  { name: 'Gear', label: 'Systems', Icon: Gear },
  { name: 'GitBranch', label: 'Git Branch', Icon: GitBranch },
  { name: 'Globe', label: 'Web', Icon: Globe },
  { name: 'Graph', label: 'Graph', Icon: Graph },
  { name: 'HardDrive', label: 'Operating System', Icon: HardDrive },
  { name: 'InfinityIcon', label: 'Infinity', Icon: InfinityIcon },
  { name: 'Eye', label: 'Vision', Icon: Eye },
  { name: 'Laptop', label: 'Laptop', Icon: Laptop },
  { name: 'Lightbulb', label: 'Ideas', Icon: Lightbulb },
  { name: 'MathOperations', label: 'Math', Icon: MathOperations },
  { name: 'Network', label: 'Network', Icon: Network },
  { name: 'PaintBrush', label: 'Design', Icon: PaintBrush },
  { name: 'Palette', label: 'Palette', Icon: Palette },
  { name: 'PuzzlePiece', label: 'Puzzle', Icon: PuzzlePiece },
  { name: 'Cpu', label: 'Processor', Icon: Cpu },
  { name: 'Robot', label: 'Robot', Icon: Robot },
  { name: 'Rocket', label: 'Rocket', Icon: Rocket },
  { name: 'Ruler', label: 'Ruler', Icon: Ruler },
  { name: 'Scan', label: 'Scan', Icon: Scan },
  { name: 'ShieldCheck', label: 'Security', Icon: ShieldCheck },
  { name: 'Sigma', label: 'Sigma', Icon: Sigma },
  { name: 'Sparkle', label: 'Sparkle', Icon: Sparkle },
  { name: 'Stack', label: 'Stack', Icon: Stack },
  { name: 'Student', label: 'Student', Icon: Student },
  { name: 'Target', label: 'Target', Icon: Target },
  { name: 'Terminal', label: 'Terminal', Icon: Terminal },
  { name: 'TerminalWindow', label: 'Terminal Window', Icon: TerminalWindow },
  { name: 'TreeStructure', label: 'Tree', Icon: TreeStructure },
  { name: 'Vault', label: 'Vault', Icon: Vault },
  { name: 'Waveform', label: 'Waveform', Icon: Waveform },
  { name: 'WifiHigh', label: 'Networking', Icon: WifiHigh },
  { name: 'Wrench', label: 'Tools', Icon: Wrench },
]

export function getIconOptionByName(name) {
  return ADMIN_ICON_OPTIONS.find(option => option.name === name) ?? ADMIN_ICON_OPTIONS[0]
}

export function getIconNameForComponent(Icon) {
  return ADMIN_ICON_OPTIONS.find(option => option.Icon === Icon)?.name ?? null
}
