// Curated emoji set for the chat/composer drawer's Emoji tab. Flat and
// searchable by name rather than grouped by category — the drawer's grid
// has no room for category headers at chat-input scale.
export const EMOJI_ITEMS = [
  { char: '😀', name: 'grinning face' },
  { char: '😂', name: 'face with tears of joy' },
  { char: '🤣', name: 'rolling on the floor laughing' },
  { char: '😊', name: 'smiling face' },
  { char: '😍', name: 'heart eyes' },
  { char: '😘', name: 'face blowing a kiss' },
  { char: '😎', name: 'smiling face with sunglasses cool' },
  { char: '🤔', name: 'thinking face' },
  { char: '🙃', name: 'upside down face' },
  { char: '😉', name: 'winking face' },
  { char: '😢', name: 'crying face sad' },
  { char: '😭', name: 'loudly crying face sobbing' },
  { char: '😡', name: 'angry face' },
  { char: '🥳', name: 'partying face celebrate' },
  { char: '😴', name: 'sleeping face tired' },
  { char: '😱', name: 'screaming face shocked scared' },
  { char: '🥺', name: 'pleading face' },
  { char: '😅', name: 'sweat smile relieved' },
  { char: '🤯', name: 'exploding head mind blown' },
  { char: '🫠', name: 'melting face' },
  { char: '👍', name: 'thumbs up approve' },
  { char: '👎', name: 'thumbs down disapprove' },
  { char: '👏', name: 'clapping hands applause' },
  { char: '🙏', name: 'folded hands please thanks pray' },
  { char: '💪', name: 'flexed biceps strong' },
  { char: '🤝', name: 'handshake deal' },
  { char: '✌️', name: 'victory hand peace' },
  { char: '👋', name: 'waving hand hello bye' },
  { char: '🤷', name: 'shrug' },
  { char: '🫡', name: 'saluting face respect' },
  { char: '❤️', name: 'red heart love' },
  { char: '💜', name: 'purple heart' },
  { char: '💯', name: 'hundred points perfect' },
  { char: '🔥', name: 'fire lit hot' },
  { char: '✨', name: 'sparkles' },
  { char: '⭐', name: 'star' },
  { char: '💀', name: 'skull dead funny' },
  { char: '👀', name: 'eyes looking' },
  { char: '🎉', name: 'party popper celebrate' },
  { char: '🚀', name: 'rocket launch' },
  { char: '⚡', name: 'lightning bolt zap' },
  { char: '🐛', name: 'bug' },
  { char: '💻', name: 'laptop computer' },
  { char: '☕', name: 'coffee' },
  { char: '🍕', name: 'pizza' },
  { char: '🎮', name: 'video game controller' },
  { char: '📌', name: 'pushpin pin' },
  { char: '✅', name: 'check mark done' },
  { char: '❌', name: 'cross mark no' },
  { char: '⚠️', name: 'warning' },
  { char: '❓', name: 'question mark' },
]
